import express from "express";
import { createCorsMiddleware } from "../middleware/corsMiddleware.js";
import requestSizeErrorHandler from "../middleware/requestSizeErrorHandler.js";
import securityHeaders from "../middleware/securityHeaders.js";
import authRoutes from "../routes/authRoutes.js";
import staffRoutes from "../routes/staffRoutes.js";
import salonRoutes from "../routes/salonRoutes.js";
import customerRoutes from "../routes/customerRoutes.js";
import appointmentRoutes from "../routes/appointmentRoutes.js";
import billRoutes from "../routes/billRoutes.js";
import serviceRoutes from "../routes/serviceRoutes.js";
import reviewRoutes from "../routes/reviewRoutes.js";
import salaryRoutes from "../routes/salaryRoutes.js";
import teamRoutes from "../routes/teamRoutes.js";
import revenueRoutes from "../routes/revenueRoutes.js";

const app = express();
app.set("trust proxy", 1);
app.use(securityHeaders);
app.use(createCorsMiddleware());
app.use(express.json({ limit: "10kb" }));
app.use("/api/auth", authRoutes);
app.use("/api/staff", staffRoutes);
app.use("/api/salons", salonRoutes);
app.use("/api/customers", customerRoutes);
app.use("/api/appointments", appointmentRoutes);
app.use("/api/bills", billRoutes);
app.use("/api/services", serviceRoutes);
app.use("/api/reviews", reviewRoutes);
app.use("/api/salary", salaryRoutes);
app.use("/api/team", teamRoutes);
app.use("/api/revenue", revenueRoutes);
app.use(requestSizeErrorHandler);
export default app;
